baseURL = 'https://disturbherb.github.io/'
languageCode = 'en-au'
title = '''DisturbHerb's Box'''
copyright = 'Copyright Â© 2026, DisturbHerb'
theme = 'herbportfolio'

[caches]
  [caches.images]
    dir = ':cacheDir/images'